---
os: ubuntu
dist: focal

# Use the new container infrastructure
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install ansible

stages:
  - smoketest

jobs:
  include:
    - stage: smoketest
      script:
        - ansible-playbook -i localhost provision.yml --syntax-check
        - ansible-playbook -i ci provision.yml --tags common
