---
# tasks file for awscli

- name: Install pip3
  apt:
    name: python3-pip,python-setuptools
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install awscli
  pip:
    name: awscli
    state: present
    executable: pip3
