name: integration tests
on: [pull_request]
jobs:
  one:
    name: e2e integration
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@master

      - name: install ansible
        run: |
          sudo apt-get update
          sudo apt-get install ansible

      - name: run bootstrap playbook
        env:
          ANSIBLE_FORCE_COLOR: True
        run: |
          ansible-playbook -i actions provision.yml --syntax-check
          ansible-playbook -i actions provision.yml

      - name: cancel job
        uses: andymckay/cancel-action@0.2
        if: ${{ failure() }}
