name: Main workflow
on: [push]
jobs:
  ubuntu:
    name: ubuntu integration
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@master

      - name: setup ruby env
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: lint yaml set
        run: |
          gem install yaml-lint
          yaml-lint -i $GITHUB_WORKSPACE

      - name: install ansible
        run: |
          sudo apt-get update
          sudo apt-get install ansible

      - name: run bootstrap playbook
        env:
          ANSIBLE_FORCE_COLOR: True
        run: |
          ansible-playbook -i actions provision.yml --syntax-check
          ansible-playbook -i actions provision.yml
